name: Build & Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Build Docker image
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: ./docker/cpu/Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: kokoro-fastapi:latest
          allow: network.host

      - name: Create deployment package
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./docker/cpu"
          files: |
            Dockerfile
            captain-definition
            pyproject.toml
            requirements.lock
            uv.lock
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
